User login backend
PistolRcks/web-puzzle-project pull request #22
Opened 2023-02-19 23:48 UTC by connormckellips

Created the backend capabilities for the user login on the backend

2023-02-20 00:02 UTC, Blackkirby72 requested changes
Head to `server/api/api.js` to add your route. The code would be 
`api.post('/login', login)`

Make sure to import your callback. There also really should be a unit test file for this callback in `tests/server`. I can take a look at what was wrong and see if I can figure it out.

We should also be validating any data that comes from the request body because anybody can technically make a request to the api

2023-02-20 00:02 UTC, Blackkirby72 commented on server/api/login.js
> +                res.status(500).send(err);
I would send status `401` since that's the "Unauthorized" http status

2023-02-21 01:21 UTC, lmschaff approved these changes, later dismissed

2023-02-23 18:19 UTC, PistolRcks commented
@connormckellips please use `npm install supertest` and recommit to ensure your tests work

2023-02-27 23:38 UTC, Blackkirby72 reviewed
Just some stuff I noticed. Ignore the stuff from last review about session management as I will be taking care of that with [WPP-40 - User Session Token](https://webpuzzle.atlassian.net/browse/WPP-40?atlOrigin=eyJpIjoiYWI3NDM3NGIyMWU4NGU2YTg0NTAzM2E1MGJkNDIzN2UiLCJwIjoiaiJ9)

2023-02-27 23:38 UTC, Blackkirby72 commented on server/api/login.js
> +            res.status(500).send(err);
this switched back to 401 at some point. `err` also would be null by this point, so I would send something like `401 - Username/Password combination is incorrect`

2023-02-27 23:38 UTC, Blackkirby72 commented on server/api/login.js
> +    function (err) {
I ran into some issues with `hashedPassword` not being defined. It seems like the solution is to remove this parameter and add a second `data` parameter to the callback. From what I can tell, the second parameter in `db.all()` is used to pass data into the query, but I'm not 100% on that one

2023-02-27 23:38 UTC, Blackkirby72 commented on server/api/login.js
> +          if (attemptedPassword == hashedPassword) {
This currently does not work to compare passwords since `attemptedPassword` and `hashedPassword` are actually `Buffer` objects. JavaScript pretty much stores pointers to its objects and automatically dereferences them. As is, this condition checks if the memory address of the two are the same

[Buffer.compare()](https://www.w3schools.com/nodejs/met_buffer_compare.asp) allows you to compare two Buffer objects, no require necessary

`Buffer.compare(attemptedPassword, hashedPassword) === 0` should work. As a note, you could do `!Buffer.compare()`, but since it's successful when it returns 0, I would keep the `=== 0` to avoid confusion. Otherwise it would seem like we want to enter the `if` statement when the passwords do not match

2023-02-27 23:38 UTC, Blackkirby72 commented on server/api/login.js
> +const Express = require("express");
you shouldn't need to require express

2023-03-07 16:10 UTC, PistolRcks commented
Test still failing after missing `supertest` import. Are you able to run your tests locally and maybe just a change to `package.json` just didn't get staged?

2023-03-07 18:04 UTC, Blackkirby72 reviewed
just a few comments. I'll try running unit tests in class, but those also seem fine

2023-03-07 18:04 UTC, Blackkirby72 commented on server/api/login.js
> +      salt = `${row.salt}`;
just `row.hashed_password` and `row.salt` should work here. The back ticks make a formatted string, which affects performance a little bit. JavaScript is also pretty flexible with data types, so no need to manually make them strings.

2023-03-07 18:04 UTC, Blackkirby72 commented on tests/server/login.test.js
> +//const login = require("../../server/login");
remove this comment if you don't need it

2023-03-07 18:04 UTC, Blackkirby72 commented on tests/server/login.test.js
> +const db = require("../../server/db");
I could be wrong, but I _think_ `require` statements are automatically hoisted to the start of the file, so you could likely move this line to where the other requires are. If anything breaks after doing that, just move it back, and then we know :)

2023-03-07 18:04 UTC, Blackkirby72 commented on tests/server/login.test.js
> +const db = require("../../server/db");
Jest most likely has some internal hoisting going on to make sure the `jest.mock` is called first anyway

2023-03-07 19:10 UTC, Blackkirby72 commented on package.json
> +    "react-scripts": "^2.1.3",
react-scripts should stay at version 5.0.1

2023-03-07 19:10 UTC, Blackkirby72 commented on server/api/login.js
> +var db = require("../db");
use `const`, and a merge from main will break this slightly as you'll need `{ db }` instead of just `db`

2023-03-08 17:45 UTC, closed without merging