Log out button
PistolRcks/web-puzzle-project pull request #41
Opened 2023-03-28 17:40 UTC by kantab

## For Pull Requesters/Reviewers:
All of the following should be true before making a pull request and should be inspected by reviewers:

### User Story
- [ ] Acceptance criteria are adhered to and completely finished
- [ ] All subtasks on Jira are completed

### Unit Testing
- [ ] Unit tests are finished and passing
- [ ] Code coverage is >80%

### Documentation/Style
- [ ] JSDocs are written for methods and components
- [ ] Unclear code has been documented
- [ ] Style standards are adhered to

## For Reviewers:
The following should be additionally checked by reviewers:

- [ ] Code runs locally
- [ ] Visually inspect tests; they should not simply pass, but rather they should be doing something and testing acceptance criteria
- [ ] See if "jank" code could be rewritten

## Description
Insert here the description of what your PR does.
logout button on puzzle selection page

2023-03-28 18:39 UTC, kreklb requested changes

2023-03-28 18:39 UTC, kreklb commented on client/pages/PuzzleSelectionPage/PuzzleSelectionPage.jsx
The button should probably be on the puzzle navbar component

2023-03-28 18:39 UTC, kreklb commented on client/pages/PuzzleSelectionPage/PuzzleSelectionPage.jsx
Can get rid of back button from the puzzle selection page since the log out button does the same thing and we should never be on the initial page while logged in anyways

2023-03-28 19:53 UTC, kantab commented
changes have been made

2023-03-30 19:14 UTC, connormckellips approved these changes

2023-03-30 19:15 UTC, prewe5294 approved these changes
looks good

2023-03-30 19:19 UTC, kreklb approved these changes
looks good

2023-03-30 20:05 UTC, merged