Update db.js
PistolRcks/web-puzzle-project pull request #53
Opened 2023-04-11 18:39 UTC by Blackkirby72

## For Pull Requesters/Reviewers:
All of the following should be true before making a pull request and should be inspected by reviewers:

### User Story
- [ ] Acceptance criteria are adhered to and completely finished
- [ ] All subtasks on Jira are completed

### Unit Testing
- [ ] Unit tests are finished and passing
- [ ] Code coverage is >80%

### Documentation/Style
- [ ] JSDocs are written for methods and components
- [ ] Unclear code has been documented
- [ ] Style standards are adhered to

## For Reviewers:
The following should be additionally checked by reviewers:

- [ ] Code runs locally
- [ ] Visually inspect tests; they should not simply pass, but rather they should be doing something and testing acceptance criteria
- [ ] See if "jank" code could be rewritten

## Description
Updated the database to contain columns for `profile_picture`, `profile_picture_top`, and `profile_picture_left` which allows the front end to crop as it sees fit. 

Sadly, there's no easy way to check if a column exists, and a `try/catch` wouldn't work due to some sync/async stuff going on. And, no, adding in a bunch of `async/await` didn't fix it :(

At least we'll only have to recreate the db when there are changes to it, and there is going to be some universal puzzle data

2023-04-11 19:19 UTC, PistolRcks commented
Please pull from master first then resolve your merge conflicts.

2023-04-11 19:42 UTC, lmschaff approved these changes
looks good!

2023-04-11 20:18 UTC, PistolRcks requested changes

2023-04-11 20:18 UTC, PistolRcks commented on server/db.js
> +const addColumns = (db) => {
Please add JSDocs as per the DoD.

2023-04-12 22:40 UTC, connormckellips approved these changes
Looks good to me. Syntax errors are the worst lol

2023-04-13 17:47 UTC, PistolRcks approved these changes

2023-04-13 17:47 UTC, merged